[tools]
# global tool versions go here
# you can set these with `mise use -g`
node = 'lts'
ruby = 'latest'

[settings]
# tools can read the versions files used by other version managers
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file_enable_tools = ['node', 'ruby']
