[tools]
# global tool versions go here
# you can set these with `mise use -g`
erlang = 'latest'
elixir = 'latest'
node = 'lts'
ruby = 'latest'

[settings]
# tools can read the versions files used by other version managers
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file_enable_tools = ['node', 'ruby']

env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`
