tap "heroku/brew"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "github/gh"
brew "ctags"
brew "fzf"
brew "gh"
brew "git"
brew "nvm"
brew "postgresql", restart_service: true
brew "rbenv"
brew "redis", restart_service: true
brew "ripgrep"
brew "telnet"
brew "thefuck"
brew "tldr"
brew "tree"
brew "vim"
brew "yarn", args: ["without-node"]
brew "youtube-dl"
brew "zsh"
brew "heroku/brew/heroku"
cask "font-jetbrains-mono"
cask "ngrok"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
