tap "heroku/brew"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"
tap "joshuaclayton/formulae"
brew "ctags"
brew "git"
brew "hub"
brew "nvm"
brew "postgresql", restart_service: true
brew "rbenv"
brew "redis", restart_service: true
brew "telnet"
brew "the_silver_searcher"
brew "thefuck"
brew "tree"
brew "vim"
brew "yarn", args: ["without-node"]
brew "youtube-dl"
brew "zsh-git-prompt"
brew "heroku/brew/heroku"
brew "joshuaclayton/formulae/unused"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
