[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
