[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
G = [
  ":pipe-to cat > /tmp/helix-ai",
  ":pipe cat /tmp/helix-ai | aichat 'Improve this code. Do not provide explanations.'"
]
L = [
  ":pipe-to cat > /tmp/helix-ai",
  ":sh echo 'Generating step by step explanation...'",
  ":sh cat /tmp/helix-ai | aichat 'Explain the following code block step by step.'"
]
