[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[language-server.rubocop]
command = "bundle"
args = ["exec", "rubocop", "--lsp"]

[[language]]
name = "ruby"
auto-format = true
language-servers = [
  { name = "rubocop" },
  "solargraph",
]

[[language]]
name = "vue"
auto-format = true
file-types = ["vue"]
injection-regex = "vue"
language-server = { command = "vue-language-server", args = ["--stdio"] }
roots = ["package.json"]
scope = "text.html.vue"
formatter = { command = "npx", args = ["prettier", "--parser", "vue"]}

[language.config.typescript]
tsdk = "/opt/homebrew/opt/typescript/libexec/lib/node_modules/typescript/lib"

[[language]]
name = "yaml"

[language.config.yaml]
keyOrdering = false

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
config = { "json" = { "validate" = { "enable" = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
config = { "css" = { validate = { enable = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
