[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[language-server.rubocop]
command = "bundle"
args = ["exec", "rubocop", "--lsp"]

[[language]]
name = "ruby"
auto-format = true
language-servers = [
  { name = "rubocop" },
  "solargraph",
]

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vue-language-server.config]
typescript = { tsdk = "/opt/homebrew/opt/typescript/libexec/lib/node_modules/typescript/lib" }

[[language]]
name = "vue"
scope = "source.vue"
file-types = ["vue"]
injection-regex = "vue"
roots = ["package.json"]
language-servers = ["vue-language-server"]
formatter = { command = "npx", args = ["prettier", "--parser", "vue"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "json"
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
