[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
auto-format = true

[[language]]
name = "elixir"
auto-format = true

[language-server.tailwindcss-ls]
config.tailwindCSS.includeLanguages = { "heex" = "html" }

[[language]]
name = "heex"
language-servers = [ "elixir-ls", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "json"
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "tailwindcss-ls" ]
